CREATE TABLE IF NOT EXISTS domains (
  id         SERIAL PRIMARY KEY,
  domain     TEXT    NOT NULL UNIQUE,
  label      TEXT    NOT NULL,
  is_default BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE videos ADD COLUMN IF NOT EXISTS domain_id INTEGER REFERENCES domains(id);
